
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

link_with 'TableView-Example', 'ScrollView-Example', 'CollectionView-Example'

pod 'DZNSegmentedControl', :path => '../DZNSegmentedControl.podspec'